<?php

namespace backend\controllers;

use common\events\UserActivatedEvent;
use Yii;
use yii\web\NotFoundHttpException;
use common\events\UserActivateEvent;
use common\models\ActivateLog;
use common\models\search\ActivateLogSearch;

/**
 * ActivateLogController implements the CRUD actions for ActivateLog model.
 */
class ActivateLogController extends BaseController
{

    const EVENT_USER_ACTIVATED = 'user_activated';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::EVENT_USER_ACTIVATED, ['common\components\mailer', 'activatedNotification']);
    }

    /**
     * Lists all ActivateLog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ActivateLogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ActivateLog model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ActivateLog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ActivateLog();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ActivateLog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ActivateLog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ActivateLog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ActivateLog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ActivateLog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionActivate($id)
    {
        $log = $this->findModel($id);
        $log->is_deal = 1;
        $log->expire_time += (time() - $log->created_time);
        $log->save(false);

        Yii::$app->session->setFlash('success', '开通成功');

        //触发事件
        $event = new UserActivatedEvent();
        $event->uid = $log->uid;
        $event->appName = $log->appname;

        $this->trigger(self::EVENT_USER_ACTIVATED,$event);

        return $this->redirect(Yii::$app->request->getReferrer());
    }

}
